export enum ProjectRole {
  PROJECT_ADMIN = 'PROJECT_ADMIN',
  EXECUTIVE_VIEWER = 'EXECUTIVE_VIEWER',
  DIRECTOR = 'DIRECTOR',
  PM = 'PM',
  PMO = 'PMO',
  FINANCIERO = 'FINANCIERO',
  CONTRACTOR_LEAD = 'CONTRACTOR_LEAD',
  FIELD_OPERATOR = 'FIELD_OPERATOR',
  VIEWER = 'VIEWER',
}
