export enum ProjectRole {
  PROJECT_ADMIN = 'PROJECT_ADMIN',
  DIRECTOR = 'DIRECTOR',
  PM = 'PM',
  FINANCIERO = 'FINANCIERO',
  CONTRACTOR_LEAD = 'CONTRACTOR_LEAD',
  SUPERVISOR = 'SUPERVISOR',
  RESIDENTE_OBRA = 'RESIDENTE_OBRA',
  FIELD_OPERATOR = 'FIELD_OPERATOR',
  VIEWER = 'VIEWER',
}
