export enum ProjectRole {
  PROJECT_ADMIN = 'PROJECT_ADMIN',
  DIRECTOR = 'DIRECTOR',
  PM = 'PM',
  FINANCIERO = 'FINANCIERO',
  CONTRACTOR_LEAD = 'CONTRACTOR_LEAD',
  SUPERVISOR = 'SUPERVISOR',
  RESIDENTE_OBRA = 'RESIDENTE_OBRA',
  FIELD_OPERATOR = 'FIELD_OPERATOR',
  VIEWER = 'VIEWER', // Fallback
}

export const ROLE_HIERARCHY = {
  [ProjectRole.PROJECT_ADMIN]: 100,
  [ProjectRole.DIRECTOR]: 90,
  [ProjectRole.PM]: 80,
  [ProjectRole.FINANCIERO]: 60,
  [ProjectRole.CONTRACTOR_LEAD]: 50,
  [ProjectRole.SUPERVISOR]: 40,
  [ProjectRole.RESIDENTE_OBRA]: 30,
  [ProjectRole.FIELD_OPERATOR]: 20,
  [ProjectRole.VIEWER]: 10,
};
