import { jsPDF } from "jspdf";
import { toast } from "sonner";

interface POData {
    id: string;
    vendor: string;
    project: string;
    date: string;
    status: string;
    items: {
        description: string;
        quantity: number;
        unitPrice: number;
        total: number;
    }[];
    total: number;
    currency: string;
}

export const generatePurchaseOrderPDF = (data: POData) => {
    try {
        const doc = new jsPDF();
        const lineHeight = 7;
        let y = 20;

        // --- Header ---
        doc.setFontSize(22);
        doc.setTextColor(37, 99, 235); // Blue-600
        doc.setFont("helvetica", "bold");
        doc.text("PURCHASE ORDER", 20, y);

        doc.setFontSize(10);
        doc.setTextColor(100);
        doc.setFont("helvetica", "normal");
        doc.text(`PO #${data.id.substring(0, 8).toUpperCase()}`, 20, y + 6);

        // Company Info (Right aligned)
        doc.setFontSize(14);
        doc.setTextColor(0);
        doc.setFont("helvetica", "bold");
        doc.text("Constructora Demo", 190, y, { align: "right" });

        doc.setFontSize(9);
        doc.setTextColor(100);
        doc.setFont("helvetica", "normal");
        doc.text("Av. Reforma 12-34, Zona 9", 190, y + 5, { align: "right" });
        doc.text("Guatemala City, 01009", 190, y + 10, { align: "right" });

        y += 25;

        // --- Meta Info ---
        doc.setDrawColor(220);
        doc.line(20, y, 190, y);
        y += 10;

        const leftColX = 20;
        const rightColX = 120;

        // Vendor & Project
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text("VENDOR", leftColX, y);
        doc.text("DATE", rightColX, y);

        y += 5;
        doc.setFontSize(10);
        doc.setTextColor(0);
        doc.text(data.vendor, leftColX, y);
        doc.text(data.date, rightColX, y);

        y += 10;
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text("PROJECT", leftColX, y);
        doc.text("STATUS", rightColX, y);

        y += 5;
        doc.setFontSize(10);
        doc.setTextColor(0);
        doc.text(data.project, leftColX, y);

        doc.setTextColor(data.status === 'APPROVED' ? 0 : 255);
        if (data.status === 'APPROVED') doc.setTextColor(0, 128, 0); // Green
        else doc.setTextColor(255, 165, 0); // Orange
        doc.text(data.status, rightColX, y);
        doc.setTextColor(0); // Reset

        y += 15;

        // --- Table Header ---
        doc.setFillColor(243, 244, 246); // Gray-100
        doc.rect(20, y, 170, 8, 'F');

        doc.setFontSize(8);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(100);

        const colDesc = 25;
        const colQty = 110;
        const colPrice = 140;
        const colTotal = 170;

        doc.text("DESCRIPTION", colDesc, y + 5);
        doc.text("QTY", colQty, y + 5, { align: 'center' });
        doc.text("UNIT PRICE", colPrice, y + 5, { align: 'right' });
        doc.text("TOTAL", colTotal, y + 5, { align: 'right' });

        y += 10;

        // --- Table Rows ---
        doc.setFont("helvetica", "normal");
        doc.setTextColor(0);
        doc.setFontSize(9);

        data.items.forEach((item) => {
            // Check page break
            if (y > 270) {
                doc.addPage();
                y = 20;
            }

            doc.text(item.description, colDesc, y);
            doc.text(item.quantity.toString(), colQty, y, { align: 'center' });

            const priceStr = item.unitPrice.toLocaleString(undefined, { minimumFractionDigits: 2 });
            doc.text(priceStr, colPrice, y, { align: 'right' });

            const totalStr = (item.quantity * item.unitPrice).toLocaleString(undefined, { minimumFractionDigits: 2 });
            doc.text(totalStr, colTotal, y, { align: 'right' });

            doc.setDrawColor(240);
            doc.line(20, y + 2, 190, y + 2);
            y += lineHeight;
        });

        y += 5;



        doc.setFontSize(10);
        doc.setFont("helvetica", "bold");
        doc.text("TOTAL:", 140, y + 5, { align: "right" });

        doc.setFontSize(12);
        doc.setTextColor(37, 99, 235);
        const grandTotalStr = `${data.currency} ${data.total.toLocaleString(undefined, { minimumFractionDigits: 2 })}`;
        doc.text(grandTotalStr, 190, y + 5, { align: "right" });

        // --- Footer ---
        const pageHeight = doc.internal.pageSize.height;
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.setFont("helvetica", "italic");
        doc.text("Generated by Antigravity System", 105, pageHeight - 10, { align: "center" });

        // --- Save / Download ---
        // Explicit Blob generation for cross-browser compatibility
        const fileName = `PO-${data.id.substring(0, 8)}.pdf`;
        const blob = doc.output('blob');
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = fileName;
        document.body.appendChild(link);
        link.click();

        requestAnimationFrame(() => {
            document.body.removeChild(link);
            URL.revokeObjectURL(url);
        });

        toast.success("PDF Downloaded");
        return true;

    } catch (error: any) {
        console.error("PDF Gen Error:", error);
        toast.error("Failed to generate PDF");
        return false;
    }
};
